version: "3.8"
services:
  db:
    image: mysql:5.6.51
    container_name: ecoleta-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: nlwecoleta
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_PASSWORD: db_pass
      MYSQL_USER: db_user
      SERVICE_NAME: mysql
    volumes:
      - ./docker-compose/mysql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    networks:
      - net-ecoleta

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    image: ecoleta:latest
    container_name: ecoleta-app
    restart: unless-stopped
    environment: 
        HOSTDB: ecoleta-db
        USERDB: root
        PASSDB: rootpass
        SCHEDB: nlwecoleta
    ports:
      - 8000:8000
    depends_on:
      - db
    networks:
      - net-ecoleta

networks:
  net-ecoleta:
    driver: bridge